dragdrop/app/urls.py
from django.urls import path
from . import views
from dragdrop import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dragdrop/dragdrop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

dragdrop/app/models.py
from django.db import models

class Image(models.Model):
    image_f = models.ImageField(upload_to='../images')
    created_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.created_at

dragdrop/app/views.py
from django.shortcuts import get_object_or_404,redirect,render
from .models import Image
from django.contrib import messages
import os
from django.conf import settings
from django.core.files.storage import FileSystemStorage

# Create your views here.
def index(request):
    # fname = '../dragdrop/images/testfiles.jpg'
    if request.method == "POST":
        updata = request.FILES['image']
        print("updata:",updata)
        print("FILES:",request.FILES)
        print("POST:",request.POST)
        print("path:",request.path)
        # f = open(fname,'wb+')
        # print("f:",f)
        if updata != None:
            fs = FileSystemStorage()
            filename = fs.save(updata.name, updata)
            uploaded_file_url = fs.url(filename)
            # for chunk in updata.chunks():
            #     f.write(chunk)
            #     print("f",f)
            # f.close()
            img = Image()
            img.image_f = uploaded_file_url
            print("uploaded_file_url:",uploaded_file_url)
            print("image_f:",img.image_f)
            img.save()
            images = Image.objects.all().order_by("-created_at")
        return render(request, 'index.html', {'images':images})
    else:
        # form = ImageForm()
        # images = Image.objects.all()
        images = Image.objects.all().order_by("-created_at")
        # return render(request, 'index.html', {'form':form ,'images':images})
        return render(request, 'index.html', {'images':images})

dragdrop/app/templates/index.html
{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html>

<head>
    <title>DragDrop</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>
<div class="container">
    <form action="{% url 'app:index' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div id="drag-drop-area">
            <div class="drag-drop-inside">
                <p class="drag-drop-info">ここにファイルをドロップ</p>
                <p>または</p>
                <p class="drag-drop-buttons"><input id="fileInput" type="file" value="ファイルを選択" name="image"></p>
                <button type="submit" class="btn btn-primary">サブミット</button>
            </div>
        </div>
    </form>
</div>

<!-- アップロードした画像を表示 -->
<!-- <img src="{{ uploaded_file_url }}" class="image-img"> -->

<div class="img-container"> 
    {% for img in images %}
        <img src="{{ img.image_f }}" class="image-img">
    {% empty %}
        <p>empty</p>
    {% endfor %}
</div>


</body>

<script type="text/javascript" src="{% static 'js/dragdrop.js' %}"></script>
</html>